- klimaland-app/src/components/Card.js
- klimaland-app/src/styles/_card.scss
- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
> Safari bugs

- klimaland-app/src/components/side-elements/List.js
- klimaland-app/src/styles/_card.scss
> Hover effect for similar LK list on postcard back 

- klimaland-app/src/components/CardCollection.js
> Section title missing

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
- labels on arrows for next card
- styling of arrow labels
> Arrow label

- klimaland-app/src/components/Canvas.js
- bugfix in canvas js
- remove main-default view loop because we need to go to LK view loop anyway
> iframe default view: close #206

- klimaland-app/src/components/Info.js
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
> How to use info

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/components/SelectionButtons.js
Reverts uclab-potsdam/klimataz#214
> Revert "fix for ui false in iframe"

- klimaland-app/src/components/Side.js
- klimaland-app/src/components/side-elements/List.js
> remove capital letter after "Im" in ranking

- klimaland-app/src/styles/_charts.scss
fixed bug that only upper half is visible in safari. (#28)
> fixed bug that only upper half is visible in safari. (#28)

- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
css solution for vertical display
close #208
> No UI vis centering cards

- klimaland-app/src/components/side-elements/Locator.js
> added update method for locator map

- klimaland-app/src/components/Side.js
> hide toggle on second size

- klimaland-app/src/components/Side.js
- klimaland-app/src/components/side-elements/Details.js
- klimaland-app/src/styles/_card.scss
- klimaland-app/src/styles/_config.scss
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
Tested on:
768 x 896 and smaller
> Minitablet view

- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
- klimaland-app/src/components/side-elements/vis/EnIndustry.js
- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/components/side-elements/vis/MoModalSplit.js
> Space between unit and value and no line break

- klimaland-app/src/components/LayoutManager.js
close #242
keep default LK when iframe option is comparison mode
> close #242 : keep default LK when iframe option is comparison mode

- klimaland-app/src/helpers/helperFunc.js
> update size of chart before export

- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_responsive.scss
Edit for Abfall chart toggle.
Label placeholder needs German translation, please don't delete the branch!
> change style for detail toggle, label needs translation, close #269

- klimaland-app/src/styles/_responsive.scss
> full width section dropdown.

- klimaland-app/src/components/Sources.js
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
> Sources box styling

- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
> reformat Co2

- klimaland-app/src/components/Side.js
- klimaland-app/src/styles/_card.scss
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
close #286 
please check again manually when conflicts arise after merging the resize branch, there might be conflicts in the responsive css because I restructured it a bit earlier
> Overlay bugfix

- klimaland-app/src/components/Side.js
- klimaland-app/src/styles/_card.scss
- get rid of last line in export text side list
> Export text side

- klimaland-app/index.html
- klimaland-app/src/components/Side.js
- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
set iframe to berlin 
half solved the heating labels issue
> Building heating labels

- klimaland-app/src/components/Sources.js
- klimaland-app/src/components/side-elements/vis/EnPrimaryEnergy.js
- klimaland-app/src/styles/main.scss
> fix for EnPrimaryEnergy label arrow overlapping

- klimaland-app/src/components/Info.js
- klimaland-app/src/components/Sources.js
- klimaland-app/src/styles/_responsive.scss
- klimaland-app/src/styles/main.scss
- fixed position of close button for source & help box
- I needed to move the button outside of the text container, which is why I needed to restructure the html and css
- added responsive design
close #274
> Close button info box

- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
> fix Labels heating

- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
- klimaland-app/src/styles/_charts.scss
> fix for button on trash details

- klimaland-app/src/components/Sources.js
> fix link in new tab

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/components/SelectionButtons.js
- klimaland-app/src/components/UIContext.js
- klimaland-app/src/components/side-elements/List.js
- klimaland-app/src/styles/_card.scss
close #355 
also: use react.context for storing ui param
> No clickable list UI

- klimaland-app/src/components/side-elements/vis/EnPrimaryEnergy.js
- klimaland-app/src/components/side-elements/vis/GeAvgHeating.js
> Update description and units

- klimaland-app/src/components/side-elements/List.js
- klimaland-app/src/styles/_card.scss
> prevent double clicking. 

- klimaland-app/src/components/side-elements/List.js
- klimaland-app/src/styles/_card.scss
Reverts uclab-potsdam/klimataz#368
the flipping is a bit weird now
> Revert "prevent double clicking. "

- klimaland-app/src/components/Canvas.js
> Germany as default for wrong iframe options

- klimaland-app/src/components/Canvas.js
> iframe comparison view: have all sections in list but selected one on top

- klimaland-app/src/components/Side.js
- klimaland-app/src/styles/_card.scss
> update download hover label text

- klimaland-app/src/components/Card.js
- tested on my iphone
solve #248
> higher treshold for swipe trigger

- klimaland-app/src/components/CardCollection.js
- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/styles/_card.scss
I accidentally did two separate issues in one branch :/
- changed label of download button
close #411 
- filtered textData to match drowdown options of Landkreise
close #408
> Download label & filtered text data

- klimaland-app/src/components/side-elements/Locator.js
close #393 
the map does not redraw on resize still, but at least the dimensions of the Map are correct and not overlapping with the text.
> update locator dimensions on resize

- klimaland-app/src/components/CardCollection.js
- klimaland-app/src/components/side-elements/Locator.js
- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
- klimaland-app/src/components/side-elements/vis/LaAnimalCount.js
- klimaland-app/src/components/side-elements/vis/LaAnimalDensity.js
- klimaland-app/src/helpers/helperFunc.js
#312 (not closed)
- removed unused variables
- change "==" operator
- solved some other minor warnings
> remove unused variables, change "==" operator

- klimaland-app/src/components/Info.js
- klimaland-app/src/components/LayoutManager.js
> Adapt help box to view

- klimaland-app/src/components/side-elements/vis/LaAnimalCount.js
- klimaland-app/src/components/side-elements/vis/LaAnimalDensity.js
> Adjust agriculture nan labels

- klimaland-app/src/styles/_card.scss
> Download label next card

- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/styles/_responsive.scss
> added location name on buildings postcard

- klimaland-app/src/styles/_card.scss
- klimaland-app/src/styles/main.scss
I am not sure if it works with this styling though
close #387
close #370
> Thumbnail hover titles

- klimaland-app/src/components/side-elements/Details.js
- klimaland-app/src/styles/_card.scss
#418 
the line is now only on the right side of the postcard and the text is a bit longer. If you don't like this design, we can revert the last commit of this pull request.
> Remove taz and klimaland buttons

- klimaland-app/src/components/SelectionButtons.js
> copy pasted desktop styles to mobile styles

- klimaland-app/src/components/Side.js
> only show download button and section when "isTopCard". 

- klimaland-app/src/styles/_card.scss
> add transparent background to side-container to solve bug #349

- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/components/side-elements/vis/LaAnimalCount.js
- klimaland-app/src/components/side-elements/vis/LaAnimalDensity.js
- klimaland-app/src/components/side-elements/vis/MoCarDensity.js
- klimaland-app/src/components/side-elements/vis/MoModalSplit.js
> taz adjustements to text

- klimaland-app/src/components/side-elements/Locator.js
- klimaland-app/src/styles/_charts.scss
close #457 
close #460 
I did not do tooltips for the zoom map though, if we still want it, we could create a new issue
> Locator tooltip

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/styles/_config.scss
- klimaland-app/src/styles/_responsivenew.scss
- klimaland-app/src/styles/main.scss
- changed card size
- adjusted close button
- moved arrows below card
- minor adjustments to top UI bar (not finished)
- conditional word art title visible depending on size
> UI responsive

- klimaland-app/src/styles/_responsivenew.scss
- pastes flip button fix to the right position in css
> redo fix for flip button

- klimaland-app/src/styles/_responsivenew.scss
added back side css for phones
> Backside phones

- klimaland-app/src/components/side-elements/vis/LaAnimalCount.js
> changed to sqrt scale value to radius

- klimaland-app/index.html
- klimaland-app/src/styles/_responsivenew.scss
- added tablet size (below desktop) to responsive css
- moved all my code for Schwerpunkt into below tablet
- updated ratio for header & chart for tablets
> Tablet backside

- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_config.scss
- klimaland-app/src/styles/_responsivenew.scss
redesign of new buildings legend for different responsive modes
> Newbuildings chart responsive

- klimaland-app/src/styles/_responsivenew.scss
full height of backside (bug fix after merge)
> Bug fix backside

- klimaland-app/src/components/Canvas.js
> use total lk name in canvas js function

- klimaland-app/src/components/side-elements/List.js
"auch im mittleren drittel"
#342
> change title of ranking list

- klimaland-app/src/components/Side.js
- klimaland-app/src/components/side-elements/vis/LaAnimalDensity.js
- klimaland-app/src/components/side-elements/vis/MoModalSplit.js
> Fixing small issues

- klimaland-app/src/components/side-elements/vis/MoModalSplit.js
- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_responsivenew.scss
> style of new labels #513

- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/styles/_charts.scss
- klimaland-app/src/styles/_responsivenew.scss
changed new buildings chart so it looks more like the print versions
> Adapt small printed postcard design changes

- klimaland-app/src/components/Info.js
- klimaland-app/src/styles/_responsivenew.scss
> Infobox in single postcard view & shortreads

- klimaland-app/src/components/Side.js
> bold toggle labels in responsive mode

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/styles/_responsivenew.scss
- klimaland-app/src/styles/main.scss
> Survey link

- klimaland-app/index.html
- klimaland-app/src/components/Side.js
- klimaland-app/src/styles/_responsivenew.scss
- klimaland-app/src/styles/main.scss
> Export label css fixed

- klimaland-app/src/components/Sources.js
> update sources, link fixes, added code for regionalstatistik and style polish

- klimaland-app/src/styles/_responsivenew.scss
> flip button fix

- klimaland-app/src/components/Info.js
- klimaland-app/src/styles/_responsivenew.scss
- klimaland-app/src/styles/main.scss
> adjust info container placement and height for all sizes

- klimaland-app/src/styles/_responsivenew.scss
> description size of 16px for phones

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/components/SelectionButtons.js
- klimaland-app/src/components/Side.js
- klimaland-app/src/components/side-elements/Chart.js
- klimaland-app/src/components/side-elements/List.js
- klimaland-app/src/components/side-elements/Locator.js
- klimaland-app/src/components/side-elements/Text.js
- klimaland-app/src/components/side-elements/vis/AbBiotonneWeight.js
- klimaland-app/src/components/side-elements/vis/EnIndustry.js
- klimaland-app/src/components/side-elements/vis/EnPrimaryEnergy.js
- klimaland-app/src/components/side-elements/vis/GeAvgHeating.js
- klimaland-app/src/components/side-elements/vis/GeNewBuildings.js
- klimaland-app/src/components/side-elements/vis/MoCarDensity.js
- klimaland-app/src/components/side-elements/vis/MoModalSplit.js
> solve smaller react warnings

- klimaland-app/src/styles/main.scss
> fix scrollbar

- klimaland-app/src/components/LayoutManager.js
- klimaland-app/src/components/Sources.js
- klimaland-app/src/styles/_responsivenew.scss
- klimaland-app/src/styles/main.scss
> delete umfrage button and css for it

- klimaland-app/src/styles/_charts.scss
> fix margins for newbuildings energy graph labels
